# Generated by Django 5.2.1 on 2025-05-16 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_pupils', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fam', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupils.sinf')),
            ],
        ),
    ]
